# Generated by Django 3.1.3 on 2021-07-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('facebook', models.URLField(max_length=1000)),
                ('linkedin', models.URLField(max_length=1000)),
            ],
        ),
    ]
