# Generated by Django 3.1.3 on 2021-07-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='facebook',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
