# Generated by Django 3.1.3 on 2020-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_cd', models.CharField(max_length=7)),
                ('cource_nm', models.CharField(max_length=100)),
                ('cource_info', models.CharField(max_length=1000)),
                ('subject_cd', models.CharField(max_length=2)),
                ('subject_nm', models.CharField(max_length=100)),
                ('lecture_cd', models.CharField(max_length=2)),
                ('lecture_date', models.DateTimeField()),
                ('material_cd', models.CharField(max_length=2)),
            ],
        ),
    ]
