# Generated by Django 3.1.3 on 2020-11-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='lecture_cd',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='lecture_date',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='material_cd',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='subject_nm',
        ),
    ]
